class TajoDataTypes:
    BOOLEAN = "BOOLEAN"
    INT1 = "INT1"
    INT2 = "INT2"
    INT4 = "INT4"
    INT8 = "INT8"
    FLOAT4 = "FLOAT4"
    FLOAT8 = "FLOAT8"
    TEXT = "TEXT"
    DATE = "DATE"
    TIME = "TIME"
    TIMESTAMP = "TIMESTAMP"
    BLOB = "BLOB"
    INET4 = "INET4"
    INET6 = "INET6"
    CHAR = "CHAR"
